on:
  push:

jobs:
  build:
    uses: Open-Router-Operating-System/oros-github-builder/.github/workflows/package-build.yml@sagitta
    secrets: inherit
    with:
      name: ${{ github.event.repository.name }}
      cmd: |
        # FIXME: Disabled Werror
        sed 's/if test "x$GCC" = "xyes"; then/if false; then/' -i configure.ac &&
        dpkg-buildpackage -uc -us -tc -b 
